title: Kye's Blog # 站点标题
description: | # 头像背后的信息
  <br/>
  BUPT 17th M.E <br/>
  DiDi <br/>
  <a href="mailto:hk_deyx@foxmail.com">
    <i class="fas fa-envelope"></i>
  </a>
  <a href="https://github.com/githubuserhk">
    <i class="fab fa-github"></i>
  </a>
  <br/>
  <iframe
    src="https://music.163.com/outchain/player?type=2&id=16846088&auto=0&height=32"
    width=100%
    height=52
    frameborder="no"
    border="0"
    marginwidth="0"
    marginheight="0"
  ></iframe>
url: https://smartvlc.com # 你的域名
baseurl: "" # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/assets`前也要加，即`/your_baseurl/assets`。这一项结尾不要有'/'。

jekyll-theme-WuK: # 我的主题的自定义样式都在这个命名空间
  default:
    body:
      theme-base: theme-base-0d # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
      layout-reverse: false # 开启后sidebar在右边，反之左边
      sidebar-overlay: true # 开启后正文不随sidebar移动而移动
    append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
      - | #一些页面优化标签，看不懂可跳过
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1"
        />
        <meta
          http-equiv="content-type"
          content="text/html; charset=utf-8"
        />
        <link
          rel="alternate"
          href="/feed.xml"
          title="RSS"
          type="application/rss+xml"
        />
      - | # 网站小图标，可换成你自己的图片，改href中的部分即可
        <link
          rel="apple-touch-icon-precomposed"
          href="/assets/image/Avatar.png"
        />
        <link
          rel="shortcut
          icon"
          href="/assets/image/blog-icon.png"
        />
      - | # 来自lanyon的页面样式，不要改
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/combine/gh/poole/lanyon@v1.1.0/public/css/poole.min.css,gh/poole/lanyon@v1.1.0/public/css/lanyon.min.css"
        />
      - | # 引入fontawesome图标样式
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css"
        />
      - | # 百度爬虫推送，http站点使用 http://push.zhanzhang.baidu.com/push.js
        <script
          src='https://zz.bdstatic.com/linksubmit/push.js'
          async="async"
        ></script>
      - | #<!-- Global site tag (gtag.js) - Google Analytics -->
        <script
          async="async"
          src="https://www.googletagmanager.com/gtag/js?id=UA-163543967-1"
          onload="
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'UA-163543967-1');"
        ></script>
      - | # 网站字体
        <style>
          html,
          h1,
          h2,
          h3,
          h4,
          h5,
          h6,
          .sidebar {
            font-family: "华文细黑", "Microsoft YaHei", "微软雅黑", "Times New Roman", sans-serif,"Lucida Grande", Helvetica, Arial, STXihei
          }
        </style>
      - | #修复行内图片默认样式
        <style>
          img {
            display: inline-block;
            margin: 0;
          }
        </style>
      - | # 彩虹滚动条，仅对Chrome系浏览器生效
        <style>
          ::-webkit-scrollbar {
            width: 4px;
            height: 4px;
          }
          ::-webkit-scrollbar-thumb {
            background-image: linear-gradient(45deg, Cyan 0%, Magenta 50%, Yellow 100%);
          }
        </style>
      - | # 选中字体颜色
        <style>
          ::selection {
            color: White;
            background: Black;
          }
        </style>
    sidebar: # 此配置项下是一些关于侧边栏的配置
      disable: false # 是否不显示sidebar
      avatar: # 侧边栏显示的头像
        enable: true
        img: /assets/image/Avatar.png # 头像的地址
      nav: # 导航部分的内容，你也可以自己增加文字、图标（来自fontawesome）和对应的链接
        - title: '<i class="fas fa-home fa-fw"></i> 首页'
          href: /index/
        - title: '<i class="fas fa-tags fa-fw"></i> 标签'
          href: /tags/
        - title: '<i class="fas fa-archive fa-fw"></i> 归档'
          href: /archive/
        - title: '<i class="fas fa-comments fa-fw"></i> 留言'
          href: /comments/
        - title: '<i class="fas fa-coffee fa-fw"></i> 打赏'
          href: /merger/
      simple_jekyll_search: # 侧边栏的全站搜索
        enable: true
        full_text_search: false # 可能导致缓慢的搜索和加载
        alert: | # 如果看不懂就不改
          <style>
            #sidebar-search-input {
              border-style:solid;
              border: 2px;
              border-color: red;
              width: 100%;
              border-radius:5px;
            }
            #sidebar-search-results-container {
              overflow: auto auto;
              max-height: 50vh;
            }
          </style>
          <input
            style="text-align:center"
            id="sidebar-search-input"
            placeholder="搜索本站"
            style="width:200px; height:12px"
          />
          <ol
            id="sidebar-search-results-container"
          ></ol>
          <script
            src='https://cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js'
            async='async'
            onload='
              SimpleJekyllSearch({
                json: "/assets/simple-jekyll-search/search.json",
                searchInput: document.getElementById("sidebar-search-input"),
                resultsContainer: document.getElementById("sidebar-search-results-container"),
                searchResultTemplate: `<li><a href="{url}">{title}</a></li>`,
                limit: 999,
                fuzzy: true
              })'
          ></script>
      append_to_sidebar:
        #- <script defer="defer" src="https://cdn.jsdelivr.net/gh/poole/lanyon@v1.1.0/public/js/script.min.js"></script> # 点击空白处而非按钮从而关闭侧边栏的插件，可选
        - | #修复点击侧边栏按钮回到顶部的问题
          <style>
            .sidebar-checkbox {
              display: none;
            }
            .sidebar-toggle {
              position: fixed;
            }
          </style>
        - | # 侧边栏头像效果
          <style>
            .effect {
              margin: 1rem;
              perspective: 1200px;
            }
            .effect-info {
              text-align: center;
              backface-visibility: hidden;
              position: absolute;
              top: 0;
              transform-style: preserve-3d;
            }
            .effect-img {
              z-index: 11;
              width: 100%;
              height: 100%;
              position: relative;
              transition: all 0.5s ease-in-out;
            }
            .effect-img:before {
              position: absolute;
              display: 
